<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="../../css/culture.css">
    <link rel="shortcut icon" type="image/x-icon" href="../../../img/img_pc/logo-icon.png">
    <title>Fancyoo</title>
</head>
<body>
<?php
include(__DIR__ . '/../component/header.phtml');
?>

<div class="mobileBar">
    <img class="fancyooLogo" src="../../../img/img_pc/logo.png">
    <a class="homeLinke" href="/">官网首页</a>
</div>

<div class="main container-fluid">
    <img class="banner img-responsive" src="../../../img/img_pc/cultureBanner.jpg">

    <div class="content container-fluid">
        <div class="introduceContainer">
            <div class="row">
                <div class="col-sm-12 ">
                    <h3 class="title">公司介绍</h3>
                    <br>
                    <P class="text-part">北京无界光合科技有限公司成立于2015年7月，是一家专注于交互式娱乐生活的创新型移动互联网科技公司，公司总部位于北京。“让世界无界”是北京
                        无界光合科技有限公司的愿景。用艺术情怀做产品，用极客精神做细节，用互联网模式做服务，致力于让每个人，都能享受科技带来的更真挚的生活。公
                        司致力于为广大用户提供基于手机和其他个人移动设备的娱乐、视频软硬件产品。现有自主研发的互动游戏产品“Fancyoo”，为广大的移动互联网用户
                        提供互动游戏服务。我们的创业团队成员是来自360、微软、乐元素、新浪等国际企业的顶尖人才。</>
                    <br>
                    <p>北京无界光合科技有限公司立志成为具有国际品牌的创新型公司，与国际趋势和潮流接轨，向大众市场推送最符合用户需要的互动娱乐产品。</P>
                </div>

            </div>
        </div>
        <div class="companyIntroduce">
            <div class="row">
                <div class="col-md-6 col-xs-12">
                    <div class="topContent">
                        <h3 class="title">2015</h3>
                        <P>因“让世界无界”的愿望和“技术改变世界”的简单理想</P>
                        <P>我们走到一起</P>
                    </div>
                    <div class="rightLineContainer">
                        <span class="lineBottom"></span>
                        <span class="lineCorner"></span>
                        <span class="lineRight"></span>
                    </div>
                    <div class="bottomContent">
                        <P>2015年7月，北京无界光合科技有限公司正式成立。我们希望，
                            我们能够打通虚拟世界和真实世界的边界，缩短人与人之间在真
                            实世界中的距离，更重要的是打通心灵和心灵之间的距离。</P>
                        <br>
                        <P>将MR/AR/VR与计算视觉等技术融合，用面向未来的技术，构建下一代视觉技术平台是我们的理想。
                            为了实现这一理想，我们设计实现了世界领先水平的VR头盔和AR眼镜。利用我们自己设计的动作捕捉设备，可以在虚拟世界中畅游。</p>
                        <br>
                        <P>为了实现这一理想，我们构建了VR虚拟现实技术平台，在视频高压缩比编解码和传输技术，人脸识别，VR/AR图像混合等基础技术上进入了深入的研究。</P>
                        <br>
                        <P>为了实现这一理想，我们还构建了虚拟世界所需要的娱乐和内容。</P>
                    </div>
                </div>
            </div>

            <div class="row offectRow-2016">
                <div class="col-md-6 col-md-offset-6 col-xs-12">
                    <div class="topContent">
                        <h3 class="title">2016</h3>
                        <P>在直播和短视频的热潮中，我们保持了冷静的思考。</P>
                    </div>
                    <div class="leftLineContainer">
                        <img class="lineTail-2016" src="../../../img/img_pc/tail.png">
                        <span class="lineBottom"></span>
                        <span class="lineCorner"></span>
                        <span class="lineRight"></span>
                    </div>
                    <div class="bottomContent">
                        <P>2016年初，我们获得了包括启赋资本等国内知名投资公司的第一轮融资，随后的几个月里，我们以AR技术为基础，构建了视频转播技术平台，并率先引入人脸识别和AR技术。</P>
                        <br>
                        <p>我们开始搭建我们自己的虚实世界，用视觉技术打通虚实世界之间的界限。</p>
                        <br>
                        <p>
                            我们在虚实结合的世界中强化场景化互动和游戏化，我们为用户创造了一种新形态的游戏化社交app，让用户用摄像头玩起来。。</P>
                        <br>
                        <!--                        <p>-->
                        <!--                            我们在虚拟世界中强化场景化互动和游戏化，我们为用户创造了-->
                        <!--                            一种新形态的游戏化社交app，并和我们的先锋用户一起不断的-->
                        <!--                            完善我们的虚拟世界。</P>-->
                    </div>
                </div>
            </div>

            <div class="row offectRow-2017">
                <div class="col-md-6 col-xs-12">
                    <div class="topContent">
                        <h3 class="title">2017</h3>
                        <P>我们继续前行，和我们的先锋用户在一起。</P>
                    </div>
                    <div class="rightLineContainer">
                        <img class="lineTail-2017" src="../../../img/img_pc/tail.png">
                        <span class="lineBottom"></span>
                        <span class="lineCorner"></span>
                        <span class="lineRight-2017"></span>
                    </div>
                    <div class="bottomContent">
                        <P>我们始终在围绕着视觉技术构建一个虚实结合的世界，并和我们的先锋用户一起不断的完善它。
                            在这里，我们为陌生人提供了更加良性的交流环境。</P>
                        <br>
                        <P>在这里，我们能够一起游戏，一起成长，一起真诚的交流。</P>
                        <br>
                        <p>经过不断的完善，我们为新新人类们打造的全新形态的“Fancyoo”在这个夏天全面发布了。</p>
                        <br>
                        <p>未来将至，视觉技术、人工智能、机器人、云计算技术的融合，整个人类的体验都会被一一重塑。打造一个真诚的虚实世界，这一直是我们不变的理想。</p>

                    </div>
                </div>
            </div>

            <div class="row introduceTitle">
                <div class="col-sm-12 ">
                    <h3 class="originator-title">创始人介绍</h3>
                </div>
            </div>

            <div class="row offectRow-robin">
                <div class="col-md-6 col-xs-12">
                    <div class="topContent">
                        <P><span class="robinName">任锋</span>&nbsp;雅虎中国/核心驱动工程师。</P>
                    </div>
                    <div class="rightLineContainer">
                        <span class="lineBottom"></span>
                        <span class="lineCorner"></span>
                        <span class="lineRight-robin"></span>
                    </div>
                    <div class="bottomContent">
                        <P>2003年受邀加入雅虎中国，担任核心驱动工程师。</P>

                    </div>
                </div>
            </div>


            <div class="row offectRow-robin-2005">
                <div class="col-md-6 col-md-offset-6 col-xs-12">
                    <div class="topContent">
                        <h3 class="title">2005</h3>
                    </div>
                    <div class="leftLineContainer">
                        <img class="lineTail-robin-2005" src="../../../img/img_pc/tail.png">
                        <span class="lineBottom"></span>
                        <span class="lineCorner"></span>
                        <span class="lineRight-robin-2005"></span>
                    </div>
                    <div class="bottomContent">
                        <P>创立暴风影音，担任CTO</P>
                    </div>
                </div>
            </div>

            <div class="row offectRow-2009">
                <div class="col-md-6 col-xs-12">
                    <div class="topContent">
                        <h3 class="title">2009</h3>
                    </div>
                    <div class="rightLineContainer">
                        <img class="lineTail-robin-2009" src="../../../img/img_pc/tail.png">
                        <span class="lineBottom"></span>
                        <span class="lineCorner"></span>
                        <span class="lineRight-2009"></span>
                    </div>
                    <div class="bottomContent">
                        <P>创立游龙清风，担任CEO，创造《演义三国》游戏，腾讯开放平台第一款千万级页游。</P>
                    </div>
                </div>
            </div>

            <div class="row offectRow-robin-2012">
                <div class="col-md-6 col-md-offset-6 col-xs-12">
                    <div class="topContent">
                        <h3 class="title">2012</h3>
                    </div>
                    <div class="leftLineContainer">
                        <img class="lineTail-robin-2012" src="../../../img/img_pc/tail.png">
                        <span class="lineBottom"></span>
                        <span class="lineCorner"></span>
                        <span class="lineRight-robin-2012"></span>
                    </div>
                    <div class="bottomContent">
                        <P>游龙清风与乐元素合并，任职SVP，协力打造《开心消消乐》国民级休闲游戏。</P>
                    </div>
                </div>
            </div>

            <div class="row offectRow-robin-2014">
                <div class="col-md-6 col-xs-12">
                    <div class="topContent">
                        <h3 class="title">2014</h3>
                    </div>
                    <div class="rightLineContainer">
                        <img class="lineTail-robin-2014" src="../../../img/img_pc/tail.png">
                        <span class="lineBottom"></span>
                        <span class="lineCorner"></span>
                        <span class="lineRight-2014"></span>
                    </div>
                    <div class="bottomContent">
                        <P>离开游戏行业，投身智能硬件，创造360路由器P1，
                            为360打胜了智能路由器的第一战。</P>
                    </div>
                </div>
            </div>

            <div class="row offectRow-robin-2015">
                <div class="col-md-6 col-md-offset-6 col-xs-12">
                    <div class="topContent">
                        <h3 class="title">2015</h3>
                    </div>
                    <div class="leftLineContainer">
                        <img class="lineTail-robin-2015" src="../../../img/img_pc/tail.png">
                        <span class="lineBottom"></span>
                        <span class="lineCorner"></span>
                        <span class="lineRight-robin-2015"></span>
                    </div>
                    <div class="bottomContent">
                        <P>创建无界光合科技有限公司，任CEO/董事长。</P>
                    </div>
                    <div class="endLine">
                        <img class="lineTail-robin-end" src="../../../img/img_pc/tail.png">
                        <span class="lineRight-robin-end"></span>
                    </div>

                </div>
            </div>
        </div>
    </div>

    <div class="container vision">
        <div class="banner2">
            <P class="banner2Title">打造可持续进步的团队生态</P>
            <div class="row line1">
                <div class="col-xs-4 col-sm-4 contentIcon">
                    <div>
                        <img class="lineIcon" src="../../../img/img_pc/studyIcon.png">
                        <h4 class="contentTitle">学习</h4>
                        <div class="contentDetail">
                            <P>因为我们所了解的</P>
                            <P>只是未知的一小部分</P>
                        </div>
                    </div>
                </div>
                <div class="col-xs-4 col-sm-4 contentIcon">
                    <img class="lineIcon" src="../../../img/img_pc/dopamineIcon.png">
                    <h4 class="contentTitle">多巴胺</h4>
                    <div class="contentDetail">
                        <P>快乐总是短暂的</P>
                        <P>希望才是永恒</P>
                    </div>
                </div>
                <div class="col-xs-4 col-sm-4 contentIcon">
                    <img class="lineIcon" src="../../../img/img_pc/beautyIcon.png">
                    <h4 class="contentTitle">美</h4>
                    <div class="contentDetail">
                        <P>各美其美，美人之美</P>
                        <P>美美与共，天下大同</P>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-4 col-sm-4 contentIcon">
                    <img class="lineIcon" src="../../../img/img_pc/teachIcon.png">
                    <h4 class="contentTitle">技术</h4>
                    <div class="contentDetail">
                        <P>用先进的技术让世界更美好</P>
                    </div>
                </div>
                <div class="col-xs-4 col-sm-4 contentIcon">
                    <img class="lineIcon" src="../../../img/img_pc/healthIcon.png">
                    <h4 class="contentTitle">不透支</h4>
                    <div class="contentDetail">
                        <P>社会生态，健康是最重要的</P>
                        <P>我们和用户都是生态的一部分</P>
                    </div>
                </div>
                <div class="col-xs-4 col-sm-4 contentIcon">
                    <img class="lineIcon" src="../../../img/img_pc/loveIcon.png">
                    <h4 class="contentTitle">真爱大家</h4>
                    <div class="contentDetail">
                        <P>爱自己、爱伙伴、爱世界</P>
                    </div>
                </div>
            </div>
        </div>
    </div>


</div>

<?php
include(__DIR__ . '/../component/footer.phtml');
?>

<script src="//cdn.bootcss.com/jquery/3.1.0/jquery.min.js"></script>
<script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

<script>
    $(function () {
        $(".connect").css("border-top", "4px solid #a98d54");
        $(".connect .topWord").css("color", "#a3836d");
    })

    $(".topLi").mouseenter(function () {
        $(this).find(".chosenBg").show();
    }).mouseleave(function () {
        $(this).find(".chosenBg").hide();
    })
</script>
</body>
</html>