<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="renderer" content="webkit"> <!--国产浏览器高速模式-->
    <meta name="viewport"
          content="width=device-width, initial-scale=1, minimum-scale=1.0,maximum-scale=1.0, user-scalable=no">
    <meta name="description" content="真诚与真爱相伴，在这里找到你的玩伴">
    <meta name="keywords" content="自在，合演，真诚，真爱，多巴胺，不透支">
    <link rel="shortcut icon" type="image/x-icon" href="../../../img/img_pc/logo-icon.png">
    <script src="//cdn.bootcss.com/jquery/3.1.0/jquery.min.js"></script>
    <link href="https://cdn.bootcss.com/bootstrap/3.3.4/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.bootcss.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="../../css/getPassword.css">
    <script src="//cdn.bootcss.com/jquery-cookie/1.4.1/jquery.cookie.min.js"></script>
    <script src="//cdn.bootcss.com/fastclick/1.0.6/fastclick.min.js"></script> <!--用于解决iphone中点击两下页面会放大-->
    <script src="../../js/jquery.md5.js"></script>
    <title>Fancyoo</title>
</head>
<body>
<?php
include(__DIR__ . '/../component/header.phtml');
?>

<div class="main">
    <div class="content">
        <div class="panel panel-info sideBar">
            <div class="panel-heading sideBar_title">个人中心</div>
            <div class="sideBar_data sideBar_password border_background">修改密码</div>
        </div>
        <div class="right_container">
            <div class="panel panel-info personal_changePassword">
                <div class="panel-heading changePassword_title">修改密码</div>
                <div class="password_container">
                    <div class="margin_bottom">
                        <div class="pass_align"><span class="phonenum">手机号码：</span></div>
                        <input type="text" class="form-control phonenum_input" placeholder="请输入手机号码">
                        <button type="button" class="btn btn-default send_verifyCode">发送验证码</button>
                    </div>
                    <div class="margin_bottom">
                        <div class="pass_align"><span class="verify_ocde">验证码：</span></div>
                        <input type="text" class="form-control verify_code_input" placeholder="请输入验证码">
                    </div>
                    <div class="margin_bottom">
                        <div class="pass_align"><span class="new_password">输入新密码：</span></div>
                        <input class="form-control new_password_input" type="password" placeholder="请输入新密码">
                    </div>
                    <div class="pass_align"></div>
                    <button type="button" class="btn btn-default changePassword_verify">确定</button>
                </div>
            </div>
        </div>
    </div>

    <?php
    include(__DIR__ . '/../component/footer.phtml');
    ?>
</div>

<div class="personal_remind_mask">
    <div class="alert alert-warning alert-dismissible personal_remind" role="alert">
        <p class="personal_remind_p">...</p>
        <button type="button" class="btn btn-primary closeBtn">确定</button>
    </div>
</div>

</body>
<script>
    $(function () {

        //点击发送验证码
        var sessionid;
        var verifycode;
        var phoneNum;
        var newpassword;
        var isPhone = false;
        var sending = false;
        $(".send_verifyCode").click(function () {
            checkPhone();
            if (sending == true) {
                $(".personal_remind_mask").show();
                $(".personal_remind_p").text("60秒内只可获取一次验证码");
//                alert("60秒内只可获取一次验证码");
            } else if (isPhone == true && sending == false) {
                count();//倒计时函数
                phoneNum = $(".phonenum_input").val();
                //获取验证码
                $.get('http://api3.hizizai.cn/api/v2/code', {'action': 'resetpassword', 'phonenumber': phoneNum}, function (info) {
                    console.log('info.sessionid:' + info.sessionid);
                    sessionid = info.sessionid;
                    return sessionid;
                }, 'json')
            }
        });

        //点击关闭提醒框
        $(".closeBtn").click(function () {
//            if($(".closeBtn").hasClass("pass")){
//                window.location.href = "zizai_web.php"
//            }
            $(".personal_remind_mask").hide();
        });

        //点击确定按钮
        $(".changePassword_verify").click(function () {
            checkPhone();
            console.log('sessionid:' + sessionid);
            newpassword = $.md5($.md5($(".new_password_input").val())); //新密码
            verifycode = $(".verify_code_input").val(); //验证码
            console.log("verifycode:" + verifycode);
            if(newpassword!=''&& verifycode!=''&& $(".phonenum_input").val()!='' && isPhone == true){
                $.post('http://api3.hizizai.cn/api/v2/security', {
                    'phonenumber': phoneNum,
                    'password': newpassword,
                    'sessionid': sessionid,
                    'validationcode': verifycode
                }, function (data) {
                    console.log(data);
                    if (data.code == 10000) {
                        $(".personal_remind_mask").show();
                        $(".personal_remind_p").text("信息填写错误");
                    }else if(data.user.id != ''&& data.user.id !=undefined){
                        $(".personal_remind_mask").show();
                        $(".personal_remind_p").text("密码修改成功，请重新登陆");
                        $(".closeBtn").addClass("pass");
                    }
                }, 'json');
            } else{
                $(".personal_remind_mask").show();
                $(".personal_remind_p").text("请检查信息是否填写正确");
            }
        });

        //倒计时函数
        function count() {
            if ($(".phonenum_input").val() != '') {
                var num = 60;
                var time = setInterval(function () {
                    num--;
                    sending = true;
                    $(".send_verifyCode").text(num + '秒后再试');
                    if (num == 0) {
                        window.clearInterval(time);
                        $(".send_verifyCode").text("发送验证码");
                        sending = false;
                    }
                }, 1000);
            } else {
                $(".personal_remind_mask").show();
                $(".personal_remind_p").text("手机号不可为空");
            }
        }

        //检查手机号
        function checkPhone() {
            var mobileNo = $(".phonenum_input").val();
            var pattern = /(^(([0\+]\d{2,3}-)?(0\d{2,3})-)(\d{7,8})(-(\d{3,}))?$)|(^0{0,1}1[3|4|5|6|7|8|9][0-9]{9}$)/;
            if (pattern.test(mobileNo)) {
                isPhone = true;
            } else if (mobileNo == '' || mobileNo == null) {
                $(".personal_remind_mask").show();
                $(".personal_remind_p").text("手机号码不可为空");
            } else {
                $(".personal_remind_mask").show();
                $(".personal_remind_p").text("请输入正确的手机号");
//                alert("请输入正确的手机号");
            }
        }


    })
</script>
</html>