<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="renderer" content="webkit"> <!--国产浏览器高速模式-->
    <script src="//cdn.bootcss.com/jquery/3.1.0/jquery.min.js"></script>
    <link rel="shortcut icon" type="image/x-icon" href="../../img/logo-icon.png">
    <link rel="stylesheet" href="../../css/guardian.css" type="text/css">
    <script src="//cdn.bootcss.com/fastclick/1.0.6/fastclick.min.js"></script> <!--用于解决iphone中点击两下页面会放大-->
    <title>家长监护</title>
</head>
<body>
<?php
include(__DIR__ . '/../component/header.phtml');
?>

<img class="Jumbotron" src=".../../../img/img_pc/system_jumbotron.jpg">

<div class="content">
    <div class="title_bar">
        <span class="bar_system margin content_chosen">系统介绍</span>
        <span class="bar_process margin">申请流程</span>
        <span class="bar_question margin">常见问题</span>
    </div>
    <div class="system">
        <div class="system_describe">
            <h1>网络游戏家长监护系统</h1>
            <div class="system_describe_p_div">
                <img class="system_logo" src="../../../img/img_pc/systemLogo.png">
                <div class="system_p">
                    <p>
                        "网络游戏未成年人家长监护工程"是一项由中华人民共和国文化部指导，旨在加强家长对未成年人参与网络游戏的监护，引导未成年人健康、绿色参与网络游戏，和谐家庭关系的社会性公益行动。它提供一种切实可行的方法，一种家长实施监控的管道，使家长纠正部分未成年子女沉迷游戏的行为成为可能。</p>
                    <br>
                    <P>该项社会公益行动充分反映了中国网络游戏行业高度的社会责任感，对未成年玩家合法权益的关注以及对用实际行动营造和谐社会的愿望。</P>
                </div>
            </div>
        </div>
        <div class="system_introduce">
            <h1>家长监护说明</h1>
            <P>
                家长监护工程充分考虑家长的实际需求，当家长发现自己的孩子玩游戏过于沉迷的时候，由家长提供合法的监护人资质证明、游戏名称账号、以及家长对于限制强度的愿望等信息，可对处于孩子游戏沉迷状态的账号采取几种限制措施，解决未成年人沉迷网游的不良现象，如限制孩子每天玩游戏的时间区间和长度，也可以限制只有周末才可以游戏，或者完全禁止。</P>
        </div>
        <div class="system_attention">
            <h1>未成年人健康参与网络游戏提示</h1>
            <div>
                <P>
                    随着网络在青少年中的普及，未成年人接触网络游戏已经成为普遍现象。为保护未成年人健康参与游戏，在政府进一步加强行业管理的前提下，家长也应当加强监护引导。为此，我们为未成年人参与网络游戏提供以下意见：</P>
                <P>一、主动控制游戏时间。游戏只是学习、生活的调剂，要积极参与线下的各类活动，并让父母了解自己在网络游戏中的行为和体验。</P>
                <P>二、不参与可能耗费较多时间的游戏设置。不玩大型角色扮演类游戏，不玩有PK类设置的游戏。在校学生每周玩游戏不超过2小时，每月在游戏中的花费不超过10元。</P>
                <P>三、不要将游戏当作精神寄托。尤其在现实生活中遇到压力和挫折时，应多与家人朋友交流倾诉，不要只依靠游戏来缓解压力。</P>
                <P>四、养成积极健康的游戏心态。克服攀比、炫耀、仇恨和报复等心理，避免形成欺凌弱小、抢劫他人等不良网络行为习惯。</P>
                <P>五、注意保护个人信息。包括个人家庭、朋友身份信息，家庭、学校、单位地址，电话号码等，防范网络陷阱和网络犯罪。</P>
            </div>
        </div>
    </div>

    <div class="process">
        <div class="apply_process">
            <h1>家长监护申请流程</h1>
            <img class="system_logo" src="../../../img/img_pc/parentApply.png">
        </div>
        <div class="download_process">
            <h1>监护服务申请书</h1>
            <div class="process_p">
                <p>申请家长监护服务，请下载：<a href="http://zizaiv2.oss-cn-beijing.aliyuncs.com/website/apply.zip">监护服务申请文档</a></p>
                <br>
                <P>如果您的账号已被纳入家长监护系统，并且您并对此操作有疑义，请下载：<a href="http://zizaiv2.oss-cn-beijing.aliyuncs.com/website/zizai.doc">账号疑义申诉文档</a></P>
            </div>
        </div>
        <div class="process_attention">
            <h1>未成年人健康参与网络游戏提示</h1>
            <div>
                <h3>一、申请条件</h3>
                <P>1、申请人需为被监护未成年人的法定监护人；</P>
                <P>2、申请人的被监护人年龄小于18周岁；</P>
                <P>3、申请人需为大陆公民，不含港、澳、台人士。</P>
                <h3>二、申请需要提交材料：</h3>
                <P>1、监护人信息表（包含监护人的身份证明复印件）；（<a href="http://zizaiv2.oss-cn-beijing.aliyuncs.com/website/attachment1.doc">点击下载附表一</a>）</P>
                <P>2、被监护人信息表（包含被监护人所玩游戏相关信息及身份证明复印件）；（<a href="http://zizaiv2.oss-cn-beijing.aliyuncs.com/website/attachment2.doc">点击下载附表二</a>）</P>
                <P>3、填写网络游戏未成年人家长监护申请书、保证书、授权书并手工签字（需下载，填写并打印，签字）；(<a href="http://zizaiv2.oss-cn-beijing.aliyuncs.com/website/attachment3.doc">点击下载附表三</a>）</P>
                <P>4、申请人与被申请人的监护法律关系证明文件（户口簿或者其他合法有效证明文件）。</P>
                <h3>三、申请方式</h3>
                <P>您可以通过邮件联系我们：</P>
                <P>客服邮箱：kf@hifreelight.com</P>
                <h3>四、申请流程：</h3>
                <P>我公司在收到提交材料后，将在 2个工作日内进行电话回访（不含法定节假日），并对内容进行核查。资料提交合格且核对正确的情况下，由我公司对该请求予以受理；资料提交不全面的，由我公司进行回访，并提示申请人继续补充材料；资料提交不合格且不正确的，我公司有权对该请求予以拒绝，并附说明理由</P>
                <h3>五、其他要求：</h3>
                <P>1、申请人应提交较完备的申请材料，对未提供的信息要及时补充；可请熟知电脑、互联网、游戏的人员进行协助，以便提供详实资料；</P>
                <P>2、申请人应保证提交的信息真实有效；对于提供虚假信息或伪造证件，受理公司将保留进一步追究法律责任的权利。</P>
            </div>
        </div>
    </div>

    <div class="question">
        <h1>防沉迷家长监控系统FAQ</h1>
        <h3>Q：可以通过什么渠道申请家长监督未成年人账号？</h3>
        <P>A：目前您可以通过邮箱反馈，采用上门和邮箱方式进行申请</P>
        <h3>Q：什么时间可以申请？</h3>
        <P>A：正常工作日提供符服务，邮箱：kf@hifreelight.com</P>
        <h3>Q：申请监督的账号有什么要求？</h3>
        <P>A：账号所属人必须未满18周岁。</P>
        <h3>Q：申请人有什么要求？</h3>
        <P>A：1、申请人应提交较完备的申请材料，对未提供的信息要及时补充；可请熟知电脑、互联网、游戏的人员进行协助，以便提供详实资料；</P>
        <P>2、申请人应保证提交的信息真实有效；对于提供虚假信息或伪造证件，受理公司将保留进一步追究法律责任的权利。</P>
        <h3>Q：申请监督未成年人账号需要提供什么？</h3>
        <P>A：您需要提供监护人身份证复印件、账号所属人身份证复印件以及户口本复印件、如双方户籍不在一起，需要提供公安机关监护证明、被监护人信息表、监护人信息表、家长监护申请书（申请书、保证书、授权书，需要下载，填写，并打印，手工签字）</P>
        <h3>Q：申请人提交申请后，多久可以处理完成？</h3>
        <P>A：1、我们将以最快的速度进行核实处理，由于您提供的材料不同，任何步骤有疑问，我们都会与您联系。</P>
        <P>&nbsp;&nbsp;2、申请人应保证提交的信息真实有效；对于提供虚假信息或伪造证件，受理公司将保留进一步追究法律责任的权利。</P>
        <h3>Q：申请成功后，如果需要取消监督如何操作？</h3>
        <P>A：1、您可以通过上门或传真方式提供申请监督时的相关信息，申请解除监督；</P>
        <P>2、被监护账号所属人年满18周岁可提供申请监督时的相关信息进行申请结束监督；</P>
    </div>

</div>

<?php
include(__DIR__ . '/../component/footer.phtml');
?>
</body>
<script>
    $(function(){
        $(".guardian").addClass("chosen");
    });

    $(".topLi").mouseenter(function () {
        $(this).find(".chosenBg").show();
    }).mouseleave(function () {
        $(this).find(".chosenBg").hide();
    })

    $(".bar_system").click(function () {
        $(".bar_system").addClass("content_chosen");
        $(".bar_process,.bar_question").removeClass("content_chosen");
        $(".system").show();
        $(".process,.question").hide();
    });
    $(".bar_process").click(function () {
        $(".bar_process").addClass("content_chosen");
        $(".bar_system,.bar_question").removeClass("content_chosen");
        $(".process").show();
        $(".system,.question").hide();
    });
    $(".bar_question").click(function () {
        $(".bar_question").addClass("content_chosen");
        $(".bar_system,.bar_process").removeClass("content_chosen");
        $(".question").show();
        $(".system,.process").hide();
    });
</script>

</html>