<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="../../css/join.css">
    <link rel="shortcut icon" type="image/x-icon" href="../../../img/img_pc/logo-icon.png">
    <title>Fancyoo</title>
</head>
<body>
<?php
include(__DIR__ . '/../component/header.phtml');
?>
<div class="../component/main">
    <div class="content">
        <img class="banner" src="../../../img/img_pc/banner.jpg">
        <div class="describe">
            <p>这里会给你愉悦、轻松、平等的工作氛围，还能收获亲和、尊重、暖心的合作伙伴，最重要的是,</p>
            <p>你有机会展示自己无限的潜能。</p>
        </div>
        <div class="container">
            <div class="titleBar">
                <ul class="titleBarUl">
                    <li class="techBtn chosen">技术类</li>
                    <li class="productionBtn">产品类</li>
                    <li class="operateBtn">运营类</li>
                    <li class="designBtn">设计类</li>
                    <li class="othersBtn">其他</li>
                </ul>
            </div>
            <div class="jobDetail tech">
                <div class="jobTitle">
                    <span class="title1">职位</span>
                    <span class="title2">类别</span>
                    <span class="title3">工作地点</span>
                    <span class="title4">发布时间</span>
                </div>
                <div class="jobItem">
                    <div class="jobTitleItem">
                        <div class="jobName">高级PHP开发工程师</div>
                        <div class="jobType">技术类</div>
                        <div class="jobCity">北京</div>
                        <div class="jobDate">2017-9-12</div>
                    </div>
                    <div class="itemDetail">
                        <p>岗位职责</p>
                        <P>1、负责核心功能的架构与代码实现，参与开发、维护公用核心基础模块；</P>
                        <P>2、负责解决项目中的技术难点，把关开发人员的系统设计和代码质量，参与制定开发规范；</P>
                        <p>3、参与系统性能优化，保证系统的完全、稳定、快速运行。</p>
                        <br>
                        <p>任职要求：</p>
                        <P>1、计算机或者相关专业本科学历，5年以上PHP相关开发工作经验；</P>
                        <P>2、精通PHP程序设计，能够独立编写PHP应用程序，熟练掌握至少一种主流PHP开发框架(Laravel/ThinkPHP/CI/Slim)，熟练使用GIT/SVN代码管理工具；</P>
                        <P>3、熟悉缓存系统（如MemCache／Redis），具有PHP缓存技术/静态化设计方面的经验；</P>
                        <P>4、精通MySQL等关系型数据库应用系统设计及优化熟悉linux，熟悉存储引擎及存储过程, 熟悉数据库部署和调优；</P>
                        <P>5、精通 Redis，熟悉和掌握源代码管理软件（GIT优先）；</P>
                        <P>6、具有Linux上的开发经验，能够编写常用和基本的Shell脚本；</P>
                        <P>7、高度的责任心以及良好团队合作精神，有高并发后端开发和海量数据处理经验；</P>
                        <P>8、有NoSQL项目开发经验，有敏捷或流行软件开发流程的经验；</P>
                        <P>9、必须对算法有良好的理解能力、深入理解面向对象及设计模式思想、优秀的英语阅读理解能力；</P>
                        <P>10、良好的文档书写能力和代码注释习惯，对代码整洁度、可维护性有较高追求；</P>
                        <br>
                        <p>加分项非必需</p>
                        <p>1、理解DevOps;</p>
                        <p>2、参与过基于gitflow的协同开发；</p>
                        <P>3、了解Cocos引擎或者参与过网络游戏开发；</P>
                        <P>4、了解移动端适配原则；</P>
                        <P>5、使用过strongloop团队的一个以上nodejs框架；</P>
                        <P>6、研究过基于ORM 设计；</P>
                        <P>7、有大型项目开发经验；</P>
                        <P>8、有数据统计或商业分析方面的经验；</P>
                        <P>9、有人工智能相关行业经验；</P>
                        <P>10、熟悉数字货币挖矿行业者优先；</P>
                        <P>11、Comfortable with communication in English。</P>
                        <br>
                        <P>应聘此职位，简历投递至hr@hifreelight.com</p>
                        <p>简历投递格式请以“应聘职位+姓名”作为邮件标题。</P>
                    </div>
                </div>

                <div class="jobItem">
                    <div class="jobTitleItem">
                        <div class="jobName">Node.js全栈工程师</div>
                        <div class="jobType">技术类</div>
                        <div class="jobCity">北京</div>
                        <div class="jobDate">2017-9-12</div>
                    </div>
                    <div class="itemDetail">
                        <p>岗位职责</p>
                        <P>1、参与产品前后端功能的设计与研发，及持续重构；</P>
                        <P>2、完成基于nodejs/redis/postgres等技术的服务器端API开发，使之能支撑千万用户级的移动应用；</P>
                        <p>3、完成基于javascript引擎技术栈的前端功能逻辑和UI；</p>
                        <p>4、负责基于docker的产品的部署，上线后的维护和优化。</p>
                        <br>
                        <p>任职要求：</p>
                        <P>1、两年以上开发工程师经验，对Node.js以及其他新技术充满热情（如果只懂后端但有意向全栈发展也可）；</P>
                        <P>2、熟练掌握Javascript语言编程，熟悉Node.js标准库的使用，能完成相应的扩展开发；</P>
                        <P>3、具备express、promise、async等框架的使用经验，熟悉HTTP，TCP/IP网络协议，熟悉Restful API 设计；</P>
                        <P>4、精通MySQL等关系型数据库应用系统设计及优化熟悉linux，熟悉存储引擎及存储过程, 熟悉数据库部署和调优；</P>
                        <P>5、精通 Redis，熟悉和掌握源代码管理软件（GIT优先）；</P>
                        <P>6、具有Linux上的开发经验，能够编写常用和基本的Shell脚本；</P>
                        <P>7、高度的责任心以及良好团队合作精神，有高并发后端开发和海量数据处理经验；</P>
                        <P>8、有NoSQL项目开发经验，有敏捷或流行软件开发流程的经验；</P>
                        <P>9、必须对算法有良好的理解能力、深入理解面向对象及设计模式思想、优秀的英语阅读理解能力；</P>
                        <P>10、良好的文档书写能力和代码注释习惯，对代码整洁度、可维护性有较高追求；</P>
                        <br>
                        <p>加分项非必需</p>
                        <p>1、理解DevOps;</p>
                        <p>2、参与过基于gitflow的协同开发；</p>
                        <P>3、了解Cocos引擎或者参与过网络游戏开发；</P>
                        <P>4、了解移动端适配原则；</P>
                        <P>5、使用过strongloop团队的一个以上nodejs框架；</P>
                        <P>6、研究过基于ORM设计；</P>
                        <P>7、有大型项目开发经验；</P>
                        <P>8、有数据统计或商业分析方面的经验；</P>
                        <P>9、有人工智能相关行业经验；</P>
                        <P>10、熟悉数字货币挖矿行业者优先；</P>
                        <P>11、Comfortable with communication in English。</P>
                        <br>
                        <P>应聘此职位，简历投递至hr@hifreelight.com</p>
                        <p>简历投递格式请以“应聘职位+姓名”作为邮件标题。</P>
                    </div>
                </div>

                <div class="jobItem">
                    <div class="jobTitleItem">
                        <div class="jobName">游戏全栈主程</div>
                        <div class="jobType">技术类</div>
                        <div class="jobCity">北京</div>
                        <div class="jobDate">2017-9-12</div>
                    </div>
                    <div class="itemDetail">
                        <p>岗位职责</p>
                        <P>1、使用 CocosCreator 开发移动平台上社交类休闲游戏产品，
                            使用现有通信构架完成业务逻辑；
                        </P>
                        <P>2、负责功能模块和组件功能开发、UI实现；</P>
                        <p>3、配合团队完成维护工作和功能更新；</p>
                        <p>4、主导某一功能的端到端开发。</p>
                        <br>
                        <p>任职要求：</p>
                        <P>1、熟练掌握cocos2dx开发，有服务器开发经验者优先；</P>
                        <P>2、3年以上工作经验，有优秀上线作品者优先；</P>
                        <P>3、熟悉JS或H5版的优先，熟悉CocosCreator者优先；</P>
                        <P>4、熟悉图像处理，游戏算法者优先；</P>
                        <P>5、有规范的编程风格和良好的文档习惯；</P>
                        <P>6、良好的沟通和学习能力，能承受工作压力，有完整功能的独立开发能力，
                            有团队合作精神。
                        </P>
                        <br>
                        <P>应聘此职位，简历投递至hr@hifreelight.com</p>
                        <p>简历投递格式请以“应聘职位+姓名”作为邮件标题。</P>
                    </div>
                </div>

                <div class="jobItem">
                    <div class="jobTitleItem">
                        <div class="jobName">服务器端高级开发工程师</div>
                        <div class="jobType">技术类</div>
                        <div class="jobCity">北京</div>
                        <div class="jobDate">2017-9-12</div>
                    </div>
                    <div class="itemDetail">
                        <p>岗位职责</p>
                        <P>1、负责服务器端的开发架构设计和模块开发；</P>
                        <P>2、制定和执行服务器端开发流程和标准；</P>
                        <p>3、进行技术难题攻关。</p>
                        <br>
                        <p>任职要求：</p>
                        <P>1、精通至少一种以下开发语言/环境：</P>
                        <ul class="itemUl">
                            <li>Javascript/Node.js/Cocos</li>
                            <li>PHP</li>
                            <li>Objective C/iOS</li>
                            <li>Java/Android</li>
                        </ul>
                        <P>2、至少两年实际项目开发经验，有创业激情，具备较强的团队合作意识，
                            良好的编码习惯，有较强的学习能力和沟通能力；</P>
                        <P>3、深刻理解面向对象程序设计；</P>
                        <P>4、对视频、图像、多线程、内存管理、网络协议等有一定程度研究；</P>
                        <P>5、了解关系性数据库；</P>
                        <P>6、较好的英语水平；</P>
                        <P>7、有敏捷开发经验者优先；</P>
                        <P>8、熟悉iOS/Android的内存管理机制和相关SDK及开发工具者优先；</P>
                        <P>9、github与stackoverflow贡献者，对开源社区有输出，乐于分享者优先；</P>
                        <P>10、Google使用者优先(对，我们鄙视百度，百度只是用来测网络的)；</P>
                        <br>
                        <P>应聘此职位，简历投递至hr@hifreelight.com</p>
                        <p>简历投递格式请以“应聘职位+姓名”作为邮件标题。</P>

                    </div>
                </div>

                <div class="jobItem">
                    <div class="jobTitleItem">
                        <div class="jobName">软件开发工程师（2018届毕业生）</div>
                        <div class="jobType">技术类</div>
                        <div class="jobCity">北京</div>
                        <div class="jobDate">2017-9-12</div>
                    </div>
                    <div class="itemDetail">
                        <p>团队希望加入的你是这样的：</p>
                        <P>1、2018年毕业，计算机相关专业本科或硕士学历；</P>
                        <P>2、掌握至少一种以下开发语言/环境：</P>
                        <ul class="itemUl">
                            <li>Javascript/Node.js/Cocos</li>
                            <li>PHP</li>
                            <li>Objective C/iOS</li>
                            <li>Java/Android</li>
                        </ul>
                        <p>3、有激情，具备较强的团队合作意识；</p>
                        <p>4、良好的编码习惯，拥有优秀的逻辑思维能力；</p>
                        <P>5、有上进心，能够不断学习、应用新技术；</P>
                        <P>6、有较强的学习能力和沟通能力，能够迅速融入团队；</P>
                        <P>7、 Google使用者优先(对，我们鄙视百度，百度只是用来测网络的)。</P>
                        <br>
                        <p>我们能提供的：</p>
                        <P>在这里你随时可以跟小伙伴们一起开黑，或者跟妹子们一起玩各种cosplay！</P>
                        <P>对，跑步、骑行，甚至给女朋友化妆（当然包括找女朋友啦）都有持高级化妆师证书的同事教。</P>
                        <P>这里不差才艺，只差优秀的你 ！/P>
                        <P>该有的都有，别人没有的我们也有：</P>
                        <P>那些神马五险一金、弹性工作、年底双薪、股票期权、年度旅游各种福利就不说了，我们统统都有！</P>
                        <P>该有的都有，别人没有的我们也有：</P>
                        <P>每人双屏大LCD显示器，加升降桌，加各种游戏都跑得溜的开发机；</P>
                        <P>Vive VR游戏机；</P>
                        <P>无限量现磨咖啡，各种零食；</P>
                        <P>定期团建加偶尔奢华旅游。</P>
                        <br>
                        <P>应聘此职位，简历投递至hr@hifreelight.com</p>
                        <p>简历投递格式请以“应聘职位+姓名”作为邮件标题。</P>

                    </div>
                </div>

            </div>
            <div class="jobDetail production">
                <div class="jobTitle">
                    <span class="title1">职位</span>
                    <span class="title2">类别</span>
                    <span class="title3">工作地点</span>
                    <span class="title4">发布时间</span>
                </div>
                <div class="jobItem">
                    <div class="jobTitleItem">
                        <div class="jobName">社交游戏系统策划</div>
                        <div class="jobType">产品类</div>
                        <div class="jobCity">北京</div>
                        <div class="jobDate">2017-9-12</div>
                    </div>
                    <div class="itemDetail">
                        <p>岗位职责</p>
                        <P>1、积极参与并讨论产品研发方向和内容，将结果形成文档；</P>
                        <P>2、按照时间节点有质量的完成分内的工作，保证产品的各项玩法设定正确实现；</P>
                        <p>3、部门沟通，细节打磨，脑力风暴，运营参与，用户调研等等一切策划应该做的事情。</p>
                        <br>
                        <p>任职要求：</p>
                        <P>1、热爱游戏，热爱生活，喜欢与人交往，丰富的各类游戏经验；</P>
                        <P>2、一年以上游戏策划工作经验，熟练使用Word、Excel等工具；</P>
                        <P>3、熟悉社交或休闲游戏，对社交类产品有一定的理解（重点）；</P>
                        <P>4、乐观豁达，思维敏捷，有较强的理解和沟通能力；</P>
                        <P>5、强大的自我驱动力，极强的责任心，积极主动的工作作风（必须）；</P>
                        <P>6、本科以上，有休闲或社交游戏项目经验者优先。</P>
                        <br>
                        <P>应聘此职位，简历投递至hr@hifreelight.com</p>
                        <p>简历投递格式请以“应聘职位+姓名”作为邮件标题。</P>
                    </div>
                </div>

                <div class="jobItem">
                    <div class="jobTitleItem">
                        <div class="jobName">游戏数值策划</div>
                        <div class="jobType">产品类</div>
                        <div class="jobCity">北京</div>
                        <div class="jobDate">2017-9-12</div>
                    </div>
                    <div class="itemDetail">
                        <p>岗位职责</p>
                        <P>1、根据产品设计需求，搭建完整数值框架，完善各细节数值需求，形成可阅读便于沟通理解的文档；</P>
                        <P>2、根据版本计划和运营需求持续调整产品内各方面的数值体验和平衡；</P>
                        <p>3、对游戏的虚拟货币体系及赢利模式有整套的概念，能够在策划中对该内容考虑齐全。</p>
                        <br>
                        <p>任职要求：</p>
                        <P>1、以数值策划身份经历完整项目研发及上线运营经验；</P>
                        <P>2、热爱游戏，热爱生活，喜欢与人交往，丰富的各类游戏经验；</P>
                        <P>3、具备良好的数学功底和系统建模能力，熟练使用Word、Excel等工具；</P>
                        <P>4、乐观豁达，思维敏捷，有较强的理解和沟通能力；</P>
                        <P>5、强大的自我驱动力，极强的责任心，积极主动的工作作风（必须）；</P>
                        <P>6、数学或物理等相关专业毕业优先，有休闲或社交游戏项目经验者优先。</P>
                        <br>
                        <P>应聘此职位，简历投递至hr@hifreelight.com</p>
                        <p>简历投递格式请以“应聘职位+姓名”作为邮件标题。</P>
                    </div>
                </div>

            </div>
            <div class="jobDetail operate">
                <div class="jobTitle">
                    <span class="title1">职位</span>
                    <span class="title2">类别</span>
                    <span class="title3">工作地点</span>
                    <span class="title4">发布时间</span>
                </div>
                <div class="jobItem">
                    <div class="jobTitleItem">
                        <div class="jobName">游戏运营经理</div>
                        <div class="jobType">运营类</div>
                        <div class="jobCity">北京</div>
                        <div class="jobDate">2017-9-12</div>
                    </div>
                    <div class="itemDetail">
                        <p>岗位职责</p>
                        <P>1、负责移动端产品运营工作，主要包括产品测试，数据分析、用户体验、运营支持等相关工作；</P>
                        <P>2、建立数据分析模型，收集与分析运营数据，对数据分析有近乎狂热的爱好；</P>
                        <p>3、分析用户行为和需求，提炼形成产品开发需求，从运营层面对产品进行快速迭代；</p>
                        <P>4、组织并跟进产品发布，进行产品运营数据分析和渠道管理；</P>
                        <P>5、保持对竞争产品的关注，并提出合理化建议；</P>
                        <P>6、定期对产品进行分析.评估，并提出有效的分析方案，确定下一步的运营推广计划。</P>
                        <br>
                        <p>任职要求：</p>
                        <P>1、三年以上游戏运营相关经验；</P>
                        <P>2、有较好的逻辑思维能力和沟通能力，较强的数据分析能力，对数据敏感；</P>
                        <P>3、出色的沟通与规划能力、执行能力，抗压能力，拥有强烈的责任心和团队合作精神；</P>
                        <P>4、以结果为导向，责任心强、执行力强，工作积极主动、有较强的抗压能力。</P>
                        <br>
                        <P>应聘此职位，简历投递至hr@hifreelight.com</p>
                        <p>简历投递格式请以“应聘职位+姓名”作为邮件标题。</P>
                    </div>
                </div>

                <div class="jobItem">
                    <div class="jobTitleItem">
                        <div class="jobName">社群运营经理</div>
                        <div class="jobType">运营类</div>
                        <div class="jobCity">北京</div>
                        <div class="jobDate">2017-9-12</div>
                    </div>
                    <div class="itemDetail">
                        <p>岗位职责</p>
                        <P>1、根据公司战略制定运营策略，带领运营团队完成各项业务指标，保证社群的顺利运营，不断提高运营效率；</P>
                        <P>2、搭建和运营目标用户社群，对大学生生活状态有深入了解，形式以微信、QQ为主，但不限于其它兴趣群组，知乎、知道、贴吧等；</P>
                        <p>3、吸引新用户加入社群，创建社群管理机制，提升成员活跃、留存等，挖掘、维护核心用户，维护社群各方关系；</p>
                        <P>4、有策划线上、线下社群活动经验，思维活跃，对待工作积极，热情，精力充沛；</P>
                        <P>5、有制定社群运营规则、长期管理群成员关系的能力；</P>
                        <P>6.有社群运营经验，拥有兴趣方向（包括但不限于游戏、社交、club、体育、明星粉丝等）的用户资源优先。</P>
                        <br>
                        <p>任职要求：</p>
                        <P>1、本科及以上学历，具备3年以上新媒体运营或社群运营工作及管理经验；</P>
                        <P>2、有线上、线下活动策划组织经验，具有从零到一用户运营经验者优先；</P>
                        <P>3、具备良好的责任心、创新能力，沟通协调能力、执行力及团队合作精神，性格稳重、活泼，能调动社群气氛；</P>
                        <P>4、具备一定的管理经验，善于调动资源、进行资源整合，善于发展及培养团队。</P>
                        <br>
                        <P>应聘此职位，简历投递至hr@hifreelight.com</p>
                        <p>简历投递格式请以“应聘职位+姓名”作为邮件标题。</P>
                    </div>
                </div>

                <div class="jobItem">
                    <div class="jobTitleItem">
                        <div class="jobName">用户运营专员</div>
                        <div class="jobType">运营类</div>
                        <div class="jobCity">北京</div>
                        <div class="jobDate">2017-9-12</div>
                    </div>
                    <div class="itemDetail">
                        <p>岗位职责</p>
                        <P>1、负责APP的运营工作，用户拉新、用户维护、用户沟通、用户反馈意见收集整理；</P>
                        <P>2、吸引新用户加入社群，创建社群管理机制，提升成员活跃、留存等，挖掘、维护核心用户，维护用户关系；</P>
                        <br>
                        <p>任职要求：</p>
                        <P>1、有线上、线下活动策划组织经验，具有从零到一用户运营经验者优先； </P>
                        <P>2、具备良好的责任心、创新能力，沟通协调能力、执行力及团队合作精神，活泼，能调动社群气氛；</P>
                        <P>3、有用户运营经验，拥有兴趣方向（包括但不限于游戏、社交、club、体育、明星粉丝等）的用户资源优先；</P>
                        <P>4、经验不是判断您是否合适的唯一标准，如果你有想法、思维活跃、积极向上、有资源、执行力强，就差一个机会，那么请果断投简历吧！</P>
                        <br>
                        <P>应聘此职位，简历投递至hr@hifreelight.com</p>
                        <p>简历投递格式请以“应聘职位+姓名”作为邮件标题。</P>
                    </div>
                </div>

                <div class="jobItem">
                    <div class="jobTitleItem">
                        <div class="jobName">游戏体验客服</div>
                        <div class="jobType">运营类</div>
                        <div class="jobCity">北京</div>
                        <div class="jobDate">2017-9-12</div>
                    </div>
                    <div class="itemDetail">
                        <p>岗位职责</p>
                        <P>1、负责受理客户通过热线、APP、微信等方式进入的咨询解答工作；</P>
                        <P>2、负责处理客户的问题、投诉业务；</P>
                        <P>3、负责对客户的投诉一票到底的监控跟进；</P>
                        <P>4、工作中遇到问题及时处理并上报领导；</P>
                        <P>5、工作中善于发现问题，并提出有效改进建议。</P>
                        <br>
                        <p>任职要求：</p>
                        <P>1、大专及以上学历，有一定客户服务工作经验，有一定的客户服务知识和能力；</P>
                        <P>2、计算机操作熟练，打字熟练，office办公软件使用熟练；</P>
                        <P>3、具有良好的亲和力、声音甜美，沟通能力及团队合作精神。</P>
                        <br>
                        <P>应聘此职位，简历投递至hr@hifreelight.com</p>
                        <p>简历投递格式请以“应聘职位+姓名”作为邮件标题。</P>
                    </div>
                </div>

            </div>
            <div class="jobDetail desigin">
                <div class="jobTitle">
                    <span class="title1">职位</span>
                    <span class="title2">类别</span>
                    <span class="title3">工作地点</span>
                    <span class="title4">发布时间</span>
                </div>
                <div class="jobItem">
                    <div class="jobTitleItem">
                        <div class="jobName">游戏原画师</div>
                        <div class="jobType">设计类</div>
                        <div class="jobCity">北京</div>
                        <div class="jobDate">2017-9-12</div>
                    </div>
                    <div class="itemDetail">
                        <p>岗位职责</p>
                        <P>1、根据产品需求进行游戏角色及场景的原画设计工作；</P>
                        <br>
                        <p>任职要求：</p>
                        <P>1、喜爱游戏，影视，动漫等数字艺术形式；</P>
                        <P>2、热爱游戏原画事业，充满激情，能承受高度压力；</P>
                        <P>3、熟悉游戏原画作业流程，精通任意一种或多种数字绘图软件如PhotoShop、Painter、SAI等；</P>
                        <P>4、思维活跃，创意丰富，尽责进取，有良好的团队合作精神、沟通理解能力和高度执行力。</P>
                        <br>
                        <P>优先条件：</P>
                        <P>1、美术相关专业毕业，手绘能力强，基本功扎实；</P>
                        <P>2、有游戏项目完整经验；</P>
                        <P>3、擅长Q版，西式，日韩系，二次元等美术风格者；</P>
                        <br>
                        <P>应聘此职位，简历投递至hr@hifreelight.com</p>
                        <p>简历投递格式请以“应聘职位+姓名”作为邮件标题。</P>
                    </div>
                </div>

                <div class="jobItem">
                    <div class="jobTitleItem">
                        <div class="jobName">游戏UI设计师</div>
                        <div class="jobType">设计类</div>
                        <div class="jobCity">北京</div>
                        <div class="jobDate">2017-9-12</div>
                    </div>
                    <div class="itemDetail">
                        <p>岗位职责</p>
                        <P>1、根据产品需求，制定产品的UE标准；</P>
                        <P>2、设计产品所需各界面，图标以及其他一些平面需求如LOGO，网站页面等。</P>
                        <br>
                        <p>任职要求：</p>
                        <P>1、美术平面设计相关专业毕业，熟练使用Photoshop，Illustrator等相关制图软件，熟悉使用Flash者更佳；</P>
                        <P>2、需要有完整游戏项目的UI设计经验；</P>
                        <P>3、喜欢游戏，理解游戏用户需求，具备一定的人机交互学、设计心理学知识为佳；</P>
                        <P>4、思维活跃，创意丰富，尽责进取，有良好的团队合作精神、沟通理解能力和高度执行力；</P>
                        <P>5、有社交或休闲游戏的设计经验优先。</P>
                        <br>
                        <P>应聘此职位，简历投递至hr@hifreelight.com</p>
                        <p>简历投递格式请以“应聘职位+姓名”作为邮件标题。</P>
                    </div>
                </div>

                <div class="jobItem">
                    <div class="jobTitleItem">
                        <div class="jobName">Spine动画师</div>
                        <div class="jobType">设计类</div>
                        <div class="jobCity">北京</div>
                        <div class="jobDate">2017-9-12</div>
                    </div>
                    <div class="itemDetail">
                        <p>岗位职责</p>
                        <P>1、根据游戏需求，用spine制作角色动作以及建筑动作动画；</P>
                        <P>2、拆分角色素材，对拆分的部件有能力进行修补，制作2D骨骼角色动画；</P>
                        <P>3、对动画资源进行统筹管理并优化。</P>
                        <br>
                        <p>任职要求：</p>
                        <P>1、对游戏及动画有深刻认识，对人类、四足等生物运动规律有深刻的了解；</P>
                        <P>2、拥有三年以上游戏动画制作经验、熟练掌握spine；</P>
                        <P>3、有2D动作游戏项目开发经验，能良好的使用spine进行资源统筹管理优化；</P>
                        <P>4、对flash制作动画有一定了解。</P>
                        <br>
                        <P>优先条件：</P>
                        <P>1、热爱游戏事业，喜欢休闲类游戏！！！</P>
                        <P>2、有动作游戏项目经验优先；</P>
                        <P>3、拥有3A游戏项目开发经验优先。</P>
                        <br>
                        <P>应聘此职位，简历投递至hr@hifreelight.com</p>
                        <p>简历投递格式请以“应聘职位+姓名”作为邮件标题。</P>
                    </div>
                </div>

            </div>
            <div class="jobDetail others">
                <div class="jobTitle">
                    <span class="title1">职位</span>
                    <span class="title2">类别</span>
                    <span class="title3">工作地点</span>
                    <span class="title4">发布时间</span>
                </div>
                <div class="jobItem">
                    <div class="jobTitleItem">
                        <div class="jobName">招聘专家</div>
                        <div class="jobType">职能类</div>
                        <div class="jobCity">北京</div>
                        <div class="jobDate">2017-9-12</div>
                    </div>
                    <div class="itemDetail">
                        <p>岗位职责</p>
                        <P>1、依据业务部门用人需求，提供专业的招聘咨询服务，并制定招聘计划；</P>
                        <P>2、职位分析，制定详细的寻访方案，建立人才搜寻渠道；</P>
                        <P>3、通过各渠道评估、筛选，推荐合适的候选人；</P>
                        <P>4、候选人面试安排、结果反馈、offer等入职后续跟踪服务工作；</P>
                        <P>5、维护公司现有的招聘渠道，拓展新的招聘渠道，招聘创新，不断提高并优化招聘效率；</P>
                        <P>6、部门内部的招聘项目管理。</P>
                        <br>
                        <p>任职要求：</p>
                        <P>1、本科以上学历，至少3年以上招聘领域专业工作经验；</P>
                        <P>2、熟练掌握人员招聘及面试的各类工具；</P>
                        <P>3、热爱招聘工作，业务导向，数据敏感性高；</P>
                        <P>4、优秀的沟通协调、谈判能力；</P>
                        <P>5、有过大厂和创业公司背景、猎头背景优先。</P>
                        <br>
                        <P>应聘此职位，简历投递至hr@hifreelight.com</p>
                        <p>简历投递格式请以“应聘职位+姓名”作为邮件标题。</P>
                    </div>
                </div>

            </div>


        </div>
    </div>
</div>
<?php
include(__DIR__ . '/../component/footer.phtml');
?>
<script src="../../js/join.js"></script>
<script>
    $(function () {
        $(".join").css("border-top", "4px solid #a98d54");
        $(".join .topWord").css("color", "#a3836d");
    })
</script>

</body>
</html>