<!DOCTYPE html>
<html lang="en" class="htmlhidden">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <meta name="format-detection" content="telephone=no, email=no"/>
    <link href="https://cdn.bootcss.com/fullPage.js/2.9.4/jquery.fullpage.min.css" rel="stylesheet">
    <link rel="shortcut icon" type="image/x-icon" href="../../../img/img_m/logo-icon.png">
    <link rel="stylesheet" href="../../css/mobile.css">
    <title>Fancyoo</title>
</head>
<body>

<div id="fullpage">

    <div class="slideDownContainer">
        <div class="headerContainer">
            <img class="topLogo" src="../../../img/img_m/topLogo.png">
            <div class="slideBtn">
                <div class="line1 line"></div>
                <div class="line2 line"></div>
                <div class="line3 line"></div>
            </div>
        </div>
        <ul class="slideDownUl">
            <a class="homePageLink" href="/">
                <li class="slideDownLisht">
                    官网首页
                </li>
            </a>
            <a onclick="alert('敬请期待')">
                <li class="slideDownLisht">
                    玩家论坛
                </li>
            </a>
        </ul>
    </div>

    <div class="section firstPage" data-anchor="home">
        <img class="fancyooLogo" src="../../../img/img_m/facnyoo_m.png">
        <div class="downloadContainer">
            <a class="ioslink" href="https://itunes.apple.com/cn/app/fancyoo-%E8%81%8A%E5%A4%A9%E4%BA%A4%E5%8F%8B%E7%9A%84%E6%B8%B8%E6%88%8F%E5%8C%96%E7%A4%BE%E4%BA%A4%E7%A4%BE%E5%8C%BA/id1311428217?mt=8"><img
                        class="iosBtn" src="../../../img/img_m/iosBtn.png"></a>
            <a class="androidlink"
               href="http://a.app.qq.com/o/simple.jsp?pkgname=com.hifreelight.fancy"><img
                        class="androidBtn" src="../../../img/img_m/androidBtn.png"></a>
        </div>
    </div>
    <div class="section secondPage" data-anchor="meet">
        <div class="secondContainer">
            <div class="secondTile">
                <img class="mp2title" src="../../../img/img_m/mp2title.png">
            </div>
            <div class="secondContent">
                <img class="mp2content" src="../../../img/img_m/mp2content.png">
            </div>
        </div>
    </div>
    <div class="section thirdPage" data-anchor="city">
        <div class="thirdContainer">
            <div class="thirdTitle">
                <img class="mp3title" src="../../../img/img_m/mp3title.png">
            </div>
            <div class="thirdContent">
                <div class="cityContainer">
                    <img class="mp3phone" src="../../../img/img_m/mp3phone.png">
                    <div class="slidecity city1">
                        <img class="cityBeijing" src="../../../img/img_m/mp3beijing.png">
                        <img class="bjperson" src="../../../img/img_m/bjperson.png">
                    </div>
                    <div class="slidecity city2">
                        <img class="cityShanghai" src="../../../img/img_m/mp3shanghai.png">
                        <img class="shperson" src="../../../img/img_m/shperson.png">
                    </div>
                    <div class="slidecity city3">
                        <img class="cityGuangzhou" src="../../../img/img_m/mp3guangzhou.png">
                        <img class="gzperson" src="../../../img/img_m/gzperson.png">
                    </div>
                    <div class="slidecity city4">
                        <img class="cityNanjing" src="../../../img/img_m/mp3nanjing.png">
                        <img class="njperson" src="../../../img/img_m/njperson.png">
                    </div>
                    <div class="slidecity city5">
                        <img class="citySuzhou" src="../../../img/img_m/mp3suzhou.png">
                        <img class="szperson" src="../../../img/img_m/szperson.png">
                    </div>

                </div>


            </div>
        </div>
    </div>
    <div class="section fourthPage" data-anchor="game">
        <div class="fourthContainer">
            <div class="fourthTitle">
                <img class="mp4title" src="../../../img/img_m/mp4title.png">
            </div>
            <div class="fourthContent">
                <img class="mp4content" src="../../../img/img_m/mp4content.png">
            </div>
        </div>

    </div>
    <div class="section fifthPage" data-anchor="party">
        <div class="fifthContainer">
            <div class="fifthTitle">
                <img class="mp5title" src="../../../img/img_m/mp5title.png">
            </div>
            <div class="fifthContent">
                <img class="mp5content" src="../../../img/img_m/mp5yard.png">
                <img class="mp5Pets" src="../../../img/img_m/mp5pets.png">
                <div class="roomContainer">
                    <div class="room1 slideroom"></div>
                    <div class="room2 slideroom"></div>
                    <div class="room3 slideroom"></div>
                    <div class="room4 slideroom"></div>
                    <div class="room5 slideroom"></div>
                </div>
            </div>
        </div>
    </div>

    <div class="section sixthPage" data-anchor="connect">
        <div class="sixthContent">
            <img class="mp6person" src="../../../img/img_m/mp6person.png">
            <img class="mp6title" src="../../../img/img_m/mp6title.png">
            <div class="mp6info">
                <img class="mp6infoIcon" src="../../../img/img_m/mp6icon.png">
                <img class="mp6info1" src="../../../img/img_m/mp6info1.png">
                <img class="mp6info2" src="../../../img/img_m/mp6info2.png">
            </div>
        </div>
    </div>

    <div class="section footerBarContainer fp-auto-height" data-anchor="footer">
        <div class="footerContent">
            <p class="footerCompanyName">北京无界光合科技有限公司版权所有</p>
            <p>Copyright&nbsp;&nbsp;©2015-2017&nbsp;Hifreelight,&nbsp;All&nbsp;Rights&nbsp;Reserved</p>
            <p><a class="beianLink" href="http://www.miitbeian.gov.cn/" target="_blank">京ICP备15053345号-3</a>&nbsp;&nbsp;京网文（2017）1348-097
                号</p>

            <div class="cnzzContainer">
                <script type="text/javascript">var cnzz_protocol = (("https:" == document.location.protocol) ? " https://" : " http://");
                    document.write(unescape("%3Cspan id='cnzz_stat_icon_1268160576'%3E%3C/span%3E%3Cscript src='" + cnzz_protocol + "s19.cnzz.com/z_stat.php%3Fid%3D1268160576%26show%3Dpic' type='text/javascript'%3E%3C/script%3E"));</script>
            </div>

        </div>
    </div>


    <div class="wechatGuide">
        <div class="wechatMask">
            <img class="guideImg" src="../../../img/img_m/wechatGuide.png">
        </div>
    </div>


</div>


<script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
<script src="https://cdn.bootcss.com/fullPage.js/2.9.4/jquery.fullpage.min.js"></script>
<script src="../../js/mobile_2.js"></script>

<script>
    $(document).ready(function () {
        $("html").removeClass("htmlhidden");
        adapt();
        platForm();
        is_weChat();
        checkRoom();
        $('#fullpage').fullpage({
            controlArrows: false,
            resize: false,
            navigation: false,
            verticalCentered: false,
            anchors: ['home', 'meet', 'city', 'game', 'party', 'connect'],
            touchSensitivity: 5,
            afterLoad: function (anchorLink, index) {
                if (index == 3) {
                    setInterval(function () {
                        $.fn.fullpage.moveSlideRight();
                    }, 4000)
                }
                if (index == 4) {
                    setInterval(function () {
                        $.fn.fullpage.moveSlideRight();
                    }, 4000)
                }
            }
        });

    });

    function adapt() {
        var width = document.documentElement.clientWidth;
        document.documentElement.style.fontSize = width / 7.5 + 'px';
    }

    function platForm() {
        var u = navigator.userAgent;
        var isAndroid = u.indexOf('Android') > -1 || u.indexOf('Adr') > -1;
        var isiOS = !!u.match(/\(i[^;]+;( U;)? CPU.+Mac OS X/);
        if (isiOS) {
            $(".downloadBtn").click(function () {
                $(".downloadBtn").attr("href", "https://itunes.apple.com/cn/app/fancyoo-%E8%81%8A%E5%A4%A9%E4%BA%A4%E5%8F%8B%E7%9A%84%E6%B8%B8%E6%88%8F%E5%8C%96%E7%A4%BE%E4%BA%A4%E7%A4%BE%E5%8C%BA/id1311428217?mt=8");
            })
        } else if (isAndroid) {
            $(".downloadBtn").attr("href", "http://a.app.qq.com/o/simple.jsp?pkgname=com.hifreelight.fancy");
//            $(".downloadBtn").attr("href", "http://url.cn/5H7yHnI");
        }
    }


    function weGuide() {
        var weCover = $(".wechatGuide");
        $(".androidlink").click(function () {
            var u = navigator.userAgent;
            var isAndroid = u.indexOf('Android') > -1 || u.indexOf('Adr') > -1;
            var isiOS = !!u.match(/\(i[^;]+;( U;)? CPU.+Mac OS X/);
            if (isAndroid) {
                weCover.css("display", "inline-block");
            }
            weCover.click(function () {
                $(this).css("display", "none");
            })
        });
    }

    function is_weChat() {
        var ua = navigator.userAgent.toLowerCase();
        if (ua.match(/MicroMessenger/i) == "micromessenger") {
            weGuide();
        } else {
            return false;
        }
    }

    function checkRoom() {
        var num = 1, pnum = 1;
        var timer1 = window.setInterval(function () {
            num < 5 ? num++ : num = 1;
            $(".slideroom").fadeOut();
            $(".room" + num).fadeIn();
        }, 2500);

        var timer2 = window.setInterval(function () {
            pnum < 5 ? pnum++ : pnum = 1;
            $(".slidecity").fadeOut();
            $(".city" + pnum).fadeIn();
        }, 2500)
    }

</script>
</body>
</html>