<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <script src="//cdn.bootcss.com/jquery/3.1.0/jquery.min.js"></script>
    <title>downloading</title>
    <style>
        .wechatGuide {
            width: 7.5rem;
            height: 13.34rem;
            background: rgba(0, 0, 0, 0.8);
            position: fixed;
            top: 0;
            left: 0;
            z-index: 1000;
            display: none;
        }

        .guideImg {
            position: absolute;
            left: 50%;
            margin-left: -2.5rem;
            width: 5rem;
            top: 4rem;
        }

    </style>
</head>
<body>

<div class="wechatGuide">
    <div class="wechatMask">
        <img class="guideImg" src="img/wechatGuide.png">
    </div>
</div>

<script>
    window.onload = function () {
        adapt();
        is_weChat();
        var u = navigator.userAgent;
        var isAndroid = u.indexOf('Android') > -1 || u.indexOf('Adr') > -1;
        var isiOS = !!u.match(/\(i[^;]+;( U;)? CPU.+Mac OS X/);
        if (isiOS) {
            window.location.href = "https://itunes.apple.com/cn/app/fancyoo-%E8%81%8A%E5%A4%A9%E4%BA%A4%E5%8F%8B%E7%9A%84%E6%B8%B8%E6%88%8F%E5%8C%96%E7%A4%BE%E4%BA%A4%E7%A4%BE%E5%8C%BA/id1311428217?mt=8";
        } else if (isAndroid) {
            window.location.href = "http://a.app.qq.com/o/simple.jsp?pkgname=com.hifreelight.fancy";
//            window.location.href = "http://url.cn/5H7yHnI";//引至应用宝
        }
    }

    function adapt() {
        var width = document.documentElement.clientWidth;
        document.documentElement.style.fontSize = width / 7.5 + 'px';
    }

    function weGuide() {
        var weCover = $(".wechatGuide");
        var u = navigator.userAgent;
        var isAndroid = u.indexOf('Android') > -1 || u.indexOf('Adr') > -1;
        var isiOS = !!u.match(/\(i[^;]+;( U;)? CPU.+Mac OS X/);
        if (isAndroid) {
            weCover.css("display", "inline-block");
        }
    }

    function is_weChat() {
        var ua = navigator.userAgent.toLowerCase();
        if (ua.match(/MicroMessenger/i) == "micromessenger") {
            weGuide();
        } else {
            return false;
        }
    }
</script>
</body>
</html>
