<style>
    .footerBarContainer {
        position: relative;
        width: 100%;
        height: 205px;
        background: #383733;
    }

    .footerBarContainer a {
        text-decoration: none;
        color: #776859;
    }

    .footerBarContainer .footerContent {
        width: 1200px;
        top: 50px;
        position: absolute;
        left: 50%;
        margin-left: -600px;
        text-align: center;
        color: #6a6765;
        font-size: 12px;
    }

    .footerBarContainer .footerContent p {
        /*margin: 8px auto;*/
        margin-top: 5px;
        margin-bottom: 5px;
    }

    .footerBarContainer .privacy,
    .footerBarContainer .agreement,
    .footerBarContainer .recharge,
    .footerBarContainer .guardian,
    .footerBarContainer .help {
        width: 75px;
        display: inline-block;
        color: rgba(255, 255, 2550, 0.35);
        border-right: 1px solid rgba(255, 255, 2550, 0.35);
        font-size: 12px;
    }

    .footerBarContainer .privacy:hover {
        color: #cc9966;
    }

    .footerBarContainer .agreement:hover {
        color: #cc9966;
    }

    .footerBarContainer .recharge:hover {
        color: #cc9966;
    }

    .footerBarContainer .guardian:hover {
        color: #cc9966;
    }

    .footerBarContainer .help:hover {
        color: #cc9966;
    }

    .footerBarContainer .linkContainer {
        /*margin-bottom:32px;*/
    }

    .footerCompanyName {
        margin-top: 14px !important;
    }

    .footerNum {
        margin-top: 5px;
        margin-bottom: 0;
    }

    .beianLink {
        text-decoration: none;
        color: #6a6765 !important;
        cursor: pointer;
    }
</style>
<div class="section footerBarContainer fp-auto-height">
    <div class="footerContent">
        <div class="linkContainer"><a class="privacy" href="privacy.php">隐私条款</a><a class="agreement"
                                                                                    href="agreement.php">使用协议</a><a
                    class="recharge" href="recharge.php">充值中心</a><a class="guardian" href="guardian.php">家长监护</a><a
                    class="help" href="help.php">帮助中心</a></div>
        <p class="footerCompanyName">北京无界光合科技有限公司版权所有</p>
        <p>Copyright&nbsp;&nbsp;©2015-2017&nbsp;Hifreelight,&nbsp;All&nbsp;Rights&nbsp;Reserved</p>
        <p><a class="beianLink" href="http://www.miitbeian.gov.cn/" target="_blank">京ICP备15053345号-3</a></p>
        <p class="footerNum">京网文（2017）1348-097 号</p>

        <div class="cnzzContainer">
            <script type="text/javascript">var cnzz_protocol = (("https:" == document.location.protocol) ? " https://" : " http://");
                document.write(unescape("%3Cspan id='cnzz_stat_icon_1268160576'%3E%3C/span%3E%3Cscript src='" + cnzz_protocol + "s19.cnzz.com/z_stat.php%3Fid%3D1268160576%26show%3Dpic' type='text/javascript'%3E%3C/script%3E"));</script>
        </div>
    </div>

    <!--    <script type="text/javascript">var cnzz_protocol = (("https:" == document.location.protocol) ? " https://" : " http://");document.write(unescape("%3Cspan id='cnzz_stat_icon_1266399105'%3E%3C/span%3E%3Cscript src='" + cnzz_protocol + "s22.cnzz.com/z_stat.php%3Fid%3D1266399105%26show%3Dpic1' type='text/javascript'%3E%3C/script%3E"));</script>-->

</div>