<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <meta name="format-detection" content="telephone=no, email=no">
    <link rel="shortcut icon" type="image/x-icon" href="../../../img/img_share/logo-icon.png">
    <link href="https://cdn.bootcss.com/flexslider/2.6.4/flexslider.min.css" rel="stylesheet">
    <link rel="stylesheet" href="../css/encounter_debris.css">
    <title>邂逅兑奖</title>
</head>
<body>

<div class="main">
    <div class="bannerContainer">
        <div class="bannerContent flexslider">
            <ul class="slides">
                <?php
                for ($i = 0; $i < count(json_decode($activity->extra_configs)); $i++) {
                    ?>
                    <li>
                        <img id="banner<?php echo json_decode($activity->extra_configs)[$i]->id; ?>" class="banner"
                             src="<?php echo json_decode($activity->extra_configs)[$i]->banner; ?>">
                    </li>
                    <?php
                }
                ?>

            </ul>
        </div>
        <div class="bannerDescConatiner">
            <div class="descLineContainer">
                <?= $activity->description ?>
            </div>
            <div class="detailBtn">详&nbsp;情</div>
            <div class="detailBtnDown">详&nbsp;情</div>

        </div>
        <div class="borderDotted"></div>
    </div>
    <div class="rewardContainer">
        <div class="containerTitle">兑&nbsp;奖</div>
        <div class="debrisContrainer">
            <p>你的碎片数量：<span class="debrisNum"><?= $activity->user_fragment_amount ?></span></p>
        </div>
        <div class="debrisListContrainer">
            <div class="debrisItemContainer">

                <?php
                foreach ($activity->exchanges as $exchange) {
                    ?>
                    <div class="debrisItem">
                        <img class="debrisIcon" src="<?php echo $exchange->icon; ?>">
                        <div class="rewardNameContainer"
                             style="display:<?php echo $exchange->available_exchange_amount >= 0 ? 'block' : 'none' ?>">
                            <P class="rewardName"><?php echo $exchange->name; ?></P>
                            <P class="rewardCountContainer"><span
                                        class="rewardCount rewardCount<?php echo $exchange->exchange_id ?>"><?php echo $exchange->available_exchange_amount >= 0 ? '剩余：' . $exchange->available_exchange_amount . '张' : ''; ?></span>
                            </P>
                        </div>
                        <div class="rewardNameContainerNoLimit"
                             style="display:<?php echo $exchange->available_exchange_amount < 0 ? 'block' : 'none' ?>">
                            <P class="rewardName"><?php echo $exchange->name; ?></P>
                        </div>
                        <div class="exchangeBtnContainer">
                            <div class="exchangeBtn"
                                 id="<?php echo "exchange" . $exchange->exchange_id ?>"
                                 style="display: <?php echo $exchange->available_exchange_times != 0 ? 'block' : 'none' ?>">
                                <span class="exchangeCount"><?php echo $exchange->fragment_amount; ?></span>碎片兑换
                            </div>
                            <div class="exchangeBtnDone"
                                 style="display: <?php echo $exchange->available_exchange_times == 0 ? 'block' : 'none' ?>">
                                已兑换
                            </div>
                            <P class="exchangeNumContainer"><span
                                        class="exchangeNum exchangeNum<?php echo $exchange->exchange_id ?>"><?php echo $exchange->available_exchange_times >= 0 ? '剩余兑换次数：' . $exchange->available_exchange_times : '剩余兑换次数：无限'; ?></span>
                            </P>
                        </div>
                    </div>
                    <?php
                }
                ?>

            </div>
        </div>
    </div>
</div>

<div class="bannerDetailContainer">
    <div class="bannerWindow">
        <div class="windowTopBar">
            <div class="windowCloseContainer">
                <img class="closeBtnUp" src="../../../img/img_share/closeBtnUp.png">
                <img class="closeBtnDown" src="../../../img/img_share/closeBtnDown.png">
            </div>
        </div>
        <div class="windowContent">
            <!--            <img class="windowBannerIcon" src="../../../img/img_share/windowIcon.jpg">-->
            <img class="windowBannerIcon">
            <div class="starLevel"></div>
            <p class="encounterName">一起去旅行</p>
            <a class="wechatLink" href="#">找微信好友玩</a>
        </div>
        <div class="windowBottomBar">
            <a class="getAppFriendLink getAppBtn getAppFriendUp"
               href="fancyoo://match?user_id=<?= $user_id ?>">寻找有缘人</a>
            <!--            <a class="getAppFriendLink getAppBtn getAppFriendDown" href="fancyoo://match">-->
            <!--                寻找有缘人-->
            <!--            </a>-->
        </div>
    </div>
</div>

<div class="detailMaskContainer">
    <div class="detailMaskWindow">
        <div class="windowTopBar">
            <div class="detailTitle">活动详情</div>
            <div class="windowCloseContainer">
                <img class="detailcloseBtnUp " src="../../../img/img_share/closeBtnUp.png">
                <img class="detailcloseBtnDown" src="../../../img/img_share/closeBtnDown.png">
            </div>
        </div>
        <div class="detailContent">
            <P><?= $activity->rules ?></p>
        </div>
    </div>
</div>

<script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
<script src="https://cdn.bootcss.com/flexslider/2.6.4/jquery.flexslider.min.js"></script>
<script>
    $(function () {
        adapt();
        initFleSlide();
    });

    function initFleSlide() { //轮播初始化
        $(".flexslider").flexslider({
            slideshowSpeed: 2000,//展示时间间隔ms
            animationSpeed: 1000,//滚动时间ms
            touch: true,//是否支持触屏滑动
            slideshow: true,
            directionNav: true,
            controlNav: true,
            animationLoop: true,
            pauseOnAction: false,
            pauseOnHover: false,
            before: function (slider) {
                slider.pause();
                slider.play();
            }
        })
    }

    document.onreadystatechange = function () { //页面加载完成后在显示页面
        if (document.readyState == "complete") {
            $(".main").show();
        } else {
            $(".main").hide();
        }
    };


    function adapt() {
        var width = document.documentElement.clientWidth, height = document.documentElement.clientHeight;
        document.documentElement.style.fontSize = width / 7.5 + 'px';
        $(".bannerDetailContainer,.detailMaskContainer").height(height);
    }

    //    var rewardCount = 80, debrisCount = 200, exchangeNum = 1;

    //活动banner关闭按钮点击和松开状态切换
    BtnEvent(".closeBtnUp", ".closeBtnDown", ".bannerDetailContainer");

    //活动详情关闭按钮点击松开状态切换
    BtnEvent(".detailcloseBtnUp", ".detailcloseBtnDown", ".detailMaskContainer");

    //详情按钮点击和松开状态切换
    BtnEvent(".detailBtn", ".detailBtnDown", "", ".detailMaskContainer");

    //寻找有缘人点击和松开状态切换
    //        BtnEvent(".getAppFriendUp", ".getAppFriendDown");
    //寻找有缘人点击和松开状态切换,方法二
    //    $(".getAppBtn").on('touchstart', function () {
    //        $(this).removeClass("getAppFriendUp").addClass("getAppFriendDown");
    //    }).on('touchend', function () {
    //        $(this).removeClass("getAppFriendDown").addClass("getAppFriendUp");
    //
    //    });


    //兑换按钮点击和松开状态,等到服务器返回数据确定兑换成功后改变样式
    var activityId = '<?=$activity->id ?>';//活动Id
    $(".exchangeBtn").on('touchstart', function () {
//        $(this).hide().siblings(".exchangeBtnDone").show(); //防止其他的元素也相应，所以选择兄弟元素
        var fragmentCount = parseInt($(this).find(".exchangeCount").text()),
            userFragment = parseInt($(".debrisNum").text());
        console.log(fragmentCount, userFragment);
        if (userFragment >= fragmentCount) { //用户碎片够
            //发送碎片兑换请求
            var exchangeUrl = '/api/activities/' + activityId + '/exchanges',
                user_id = <?=$user_id?>;
            exchange_id = parseInt($(this).attr("id").replace(/[^0-9]/ig, ""));
            exchange_amount = 1;
            console.log(exchangeUrl, exchange_id, exchange_amount);
            exchangeEvent(exchangeUrl, user_id, exchange_id, exchange_amount)
        } else {
            alert('碎片数量不够了！');
        }

    });

    //碎片兑换接口
    function exchangeEvent(exchangeUrl, user_id, exchange_id, exchange_amount) {
        $.ajax({
            headers: {
                Authorization: 'Bearer ' + '<?=$token?>'
            },
            url: exchangeUrl,
            type: 'POST',
            data: {user_id: user_id, exchange_id: exchange_id, amount: exchange_amount},
            dataType: 'json',
            success: function (data) {
                console.log(data);
                if (data.code && data.code >= 0) {
                    alert(data.message);
                } else if (data == true) {
                    refreshCount(activityId, user_id, exchange_id);
                }
            }
        })
    }

    //兑换成功后刷新页面
    function refreshCount(id, user_id, exchange_id) {
        var refreshUrl = '/api/activities/' + id;
        $.ajax({
            headers: {
                Authorization: 'Bearer ' + '<?=$token?>'
            },
            url: refreshUrl,
            type: 'GET',
            dataType: 'json',
            data: {user_id: user_id},
            success: function (data) {
                console.log(data);
                $(".debrisNum").text(data.user_fragment_amount);
                if (data.exchanges[parseInt(exchange_id) - 1].available_exchange_times >= 0) {
                    $(".exchangeNum" + exchange_id).text("剩余兑换次数：" + data.exchanges[parseInt(exchange_id) - 1].available_exchange_times);
                }

                if (data.exchanges[parseInt(exchange_id) - 1].available_exchange_amount >= 0) {
                    $(".rewardCount" + exchange_id).text("剩余：" + data.exchanges[parseInt(exchange_id) - 1].available_exchange_amount + "张");
                }
                if (parseInt($(".exchangeNum" + exchange_id).text().replace(/[^0-9]/ig, "")) == 0) {
                    $("#exchange" + exchange_id).hide().siblings(".exchangeBtnDone").show();
                }
            }
        });

    }

    function BtnEvent(ele1, ele2, ele3, ele4) { //按钮事件
        $(ele1).on('touchstart', function () {
            $(this).hide();
            $(ele2).show();
        }).on('touchend', function () {
            $(ele2).hide();
            $(ele1).show();
            if (ele3 || ele3 != '') {
                $(ele3).hide();
            }
            if (ele4 || ele4 != '') {
                $(ele4).show();
            }
            return false; //阻止事件继续往下传递
        });
    }

    //点击活动banner进入指定主题
    $(".slides").on("click", ".banner", function () {
        var chosenBannerId = ($(this).attr("id")).replace(/[^0-9]/ig, "");
        console.log(chosenBannerId);
        $(".bannerDetailContainer").show();
        getScene(chosenBannerId);
        $(".wechatLink").attr('href', 'fancyoo://meet?scene_id=' + chosenBannerId);
    });

    function getScene(sceneId) {
        $.ajax({
            headers: {
                Authorization: 'Bearer ' + '<?=$token?>'
            },
            type: 'GET',
            dataType: 'json',
            url: '/api/encounters/sceneInfo',
            data: {
                sceneId: sceneId
            },
            success: function (data) {
                console.log(data);
                $(".windowBannerIcon").attr('src', data.Icon);
                $(".encounterName").text(decodeURIComponent(data.Scene));
                for (var m = 0; m < data.level; m++) {
                    var starItem = "<img class=\"starItem\" src=\"../../../img/img_share/starIcon.png\">";
                    $(".starLevel").append(starItem);
                }
            }
        })
    }


</script>

</body>
